### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by Bertie97** [elarivie/linter-mypy#17]
I was running a simple case:

```
a: int = "string"
```

mypy works well in the terminal environment. However, when I use linter-mypy, there will encounter an error as follows, 

```
Traceback (most recent call last): File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main "main", mod_spec) File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code exec(code, run_globals) File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mypy/main.py", line 11, in main(None) File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mypy/main.py", line 91, in main res = type_check_only(sources, bin_dir, options, flush_errors, fscache) # noqa File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mypy/main.py", line 148, in type_check_only fscache=fscache) File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mypy/build.py", line 185, in build flush_errors, fscache) File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mypy/build.py", line 285, in _build graph = dispatch(sources, manager) File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mypy/build.py", line 2398, in dispatch process_graph(graph, manager) File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mypy/build.py", line 2691, in process_graph process_stale_scc(graph, scc, manager) File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mypy/build.py", line 2823, in process_stale_scc manager.flush_errors(manager.errors.file_messages(graph[id].xpath), False) File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mypy/main.py", line 81, in flush_errors f.write(msg + '\n') UnicodeEncodeError: 'ascii' codec can't encode characters in position 38-39: ordinal not in range(128)
```

I want to know what had happened, and how to fix it.

**Comment by Bertie97** [comment]
It seems that is because my path has a non-ascii character.
